{
 "title": "작업별실행수",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "전체 실행 횟수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(tasks_scheduled_execution_seconds_count[10m]))",
     "legendFormat": "{{code_function}}"
    },
    { "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "평균 실행 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code_function) (\n  rate(tasks_scheduled_execution_seconds_sum[5m])\n)\n/\nsum by (code_function) (\n  rate(tasks_scheduled_execution_seconds_count[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "최대실행시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (code_function) (\n  tasks_scheduled_execution_seconds_max\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "작업별실행수",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code_function) (\n  increase(tasks_scheduled_execution_seconds_count[10m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}