--liquibase formatted sql

--changeset hyeseongkim:1773379423587-1
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='users'
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, nickname VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, plan VARCHAR(255) NOT NULL, score INTEGER NOT NULL, CONSTRAINT "usersPK" PRIMARY KEY (id));
--rollback DROP TABLE users;

--changeset hyeseongkim:1773379423587-2
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.table_constraints WHERE table_schema='public' AND table_name='users' AND constraint_name='UC_USERSEMAIL_COL'
ALTER TABLE users ADD CONSTRAINT UC_USERSEMAIL_COL UNIQUE (email);
--rollback ALTER TABLE users DROP CONSTRAINT UC_USERSEMAIL_COL;

--changeset hyeseongkim:1773379423587-4
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_name='app_users'
DROP TABLE app_users;
