server.port=8080

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Datasource
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=5000
spring.data.redis.connect-timeout=5000

# JWT Secret
jwt.secret=${JWT_SECRET}

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
batch.stats.cron=0 0 1 * * *
batch.ranking.cron=0 10 1 * * *

# Jackson - LocalDate? "2026-04-08" ???? ???
spring.jackson.serialization.write-dates-as-timestamps=false


# Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Pushgateway
pushgateway.url=${PUSHGATEWAY_URL:pushgateway:9091}
