url=jdbc:postgresql://localhost:5433/${POSTGRES_DB}
username=${POSTGRES_USER}
password=${POSTGRES_PASSWORD}
referenceUrl=hibernate:spring:com.todo?dialect=org.hibernate.dialect.PostgreSQLDialect&hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
diffChangeLogFile=src/main/resources/db/changelog/sql/diff-output.sql
changeLogFile=src/main/resources/db/changelog/db.changelog-master.sql
